// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/831bfcf29384302961a1897ec6da699773480a7d/jquery-mousewheel/jquery-mousewheel.d.ts
declare namespace JQueryMousewheel {
    interface JQueryMousewheelEventObject extends JQueryEventObject {
        deltaX: number;
        deltaY: number;
        deltaFactor: number;
        deltaMode: number;
        absDelta: number;
    }
}

interface JQuery {
    mousewheel(handler: (eventObject: JQueryMousewheel.JQueryMousewheelEventObject, ...args: any[]) => any): JQuery
    unmousewheel(): JQuery;
}
